### PR TITLE
Controller map autogen

### PR DESCRIPTION
**Pull request by ThatXliner**

### CODE REVIEW

**Comment by ThatXliner** [comment]
Example
image

**Comment by ThatXliner** [comment]
I even added docs

**Comment by ThatXliner** [comment]
@chaoticthegreat if you don't like the syntax, I can write a script that parses the controller binding robot code instead

**Comment by ryanabraham1** [comment]
I am not using the controller map class if that's what you are asking.

**Comment by ThatXliner** [comment]
> I am not using the controller map class if that's what you are asking.

That's so sad

**Comment by ryanabraham1** [comment]
can you not just make a script to go through robotcontainer

**Comment by realjoshuau** [comment]
Isn't parsing code from scripts notoriously hard?

**Comment by ThatXliner** [comment]
> Isn't parsing code from scripts notoriously hard?

[I just tried it, it’s not too hard](https://github.com/Team3256/bindgen) but the code structure can vary too much, preventing me from finding the right set of selects to find ASTs to parse as the button and actions. Besides, with the API, you can use English to describe the actions

**Comment by ThatXliner** [comment]
Should I merge this

**Review by realjoshuau — APPROVED** [review]
Seems good. Maybe unit tests on ControllerMapper to ensure they work?

**Review by realjoshuau — CHANGES_REQUESTED** [review]
Seems good - pass tests and I'll approve it.

**Review by realjoshuau — APPROVED** [review]
LGTM

**Pull request merged**
